#pragma once
#include "../Framework/Core/Headers.h"

namespace CE
{
	enum class EInputModifier
	{
		None = 0,
		Shift = 1 << 0,
		Control = 1 << 1,
		Alt = 1 << 2,
		Super = 1 << 3,
		CapsLock = 1 << 4,
		NumLock = 1 << 5,
	};

	CE_ENUM_BIT_OPERATORS(EInputModifier);

	enum class EInput
	{
		None,

		Keyboard_A,
		Keyboard_B,
		Keyboard_C,
		Keyboard_D,
		Keyboard_E,
		Keyboard_F,
		Keyboard_G,
		Keyboard_H,
		Keyboard_I,
		Keyboard_J,
		Keyboard_K,
		Keyboard_L,
		Keyboard_M,
		Keyboard_N,
		Keyboard_O,
		Keyboard_P,
		Keyboard_Q,
		Keyboard_R,
		Keyboard_S,
		Keyboard_T,
		Keyboard_U,
		Keyboard_V,
		Keyboard_W,
		Keyboard_X,
		Keyboard_Y,
		Keyboard_Z,

		Keyboard_0,
		Keyboard_1,
		Keyboard_2,
		Keyboard_3,
		Keyboard_4,
		Keyboard_5,
		Keyboard_6,
		Keyboard_7,
		Keyboard_8,
		Keyboard_9,

		Keyboard_F1,
		Keyboard_F2,
		Keyboard_F3,
		Keyboard_F4,
		Keyboard_F5,
		Keyboard_F6,
		Keyboard_F7,
		Keyboard_F8,
		Keyboard_F9,
		Keyboard_F10,
		Keyboard_F11,
		Keyboard_F12,
		Keyboard_F13,
		Keyboard_F14,
		Keyboard_F15,
		Keyboard_F16,
		Keyboard_F17,
		Keyboard_F18,
		Keyboard_F19,
		Keyboard_F20,
		Keyboard_F21,
		Keyboard_F22,
		Keyboard_F23,
		Keyboard_F24,
		Keyboard_F25,

		Keyboard_Keypad_0,
		Keyboard_Keypad_1,
		Keyboard_Keypad_2,
		Keyboard_Keypad_3,
		Keyboard_Keypad_4,
		Keyboard_Keypad_5,
		Keyboard_Keypad_6,
		Keyboard_Keypad_7,
		Keyboard_Keypad_8,
		Keyboard_Keypad_9,
		Keyboard_Keypad_Add,
		Keyboard_Keypad_Decimal,
		Keyboard_Keypad_Divide,
		Keyboard_Keypad_Enter,
		Keyboard_Keypad_Equal,
		Keyboard_Keypad_Multiply,
		Keyboard_Keypad_Subtract,

		Keyboard_Apostrophe,
		Keyboard_Backslash,
		Keyboard_Comma,
		Keyboard_Equal,
		Keyboard_Grave_Accent,
		Keyboard_Left_Bracket,
		Keyboard_Minus,
		Keyboard_Period,
		Keyboard_Right_Bracket,
		Keyboard_Semicolon,
		Keyboard_Slash,
		Keyboard_World_2,
		Keyboard_Backspace,
		Keyboard_Delete,
		Keyboard_End,
		Keyboard_Enter,
		Keyboard_Escape,
		Keyboard_Home,
		Keyboard_Insert,
		Keyboard_Menu,
		Keyboard_Page_Down,
		Keyboard_Page_Up,
		Keyboard_Pause,
		Keyboard_Space,
		Keyboard_Tab,
		Keyboard_Caps_Lock,
		Keyboard_Num_Lock,
		Keyboard_Scroll_Lock,

		Keyboard_Left_Alt,
		Keyboard_Left_Control,
		Keyboard_Left_Shift,
		Keyboard_Left_Super,
		Keyboard_Print_Screen,
		Keyboard_Right_Alt,
		Keyboard_Right_Control,
		Keyboard_Right_Shift,
		Keyboard_Right_Super,
		Keyboard_Down,
		Keyboard_Left,
		Keyboard_Right,
		Keyboard_Up,

		Mouse_Left,
		Mouse_Middle,
		Mouse_Right,
		Mouse_4,
		Mouse_5,
		Mouse_6,
		Mouse_7,
		Mouse_8,

		Mouse_Wheel,
		Mouse_WheelUp,
		Mouse_WheelDown,

		Mouse_X,
		Mouse_Y,
	};
}
